"use strict";

/*
    What's DOM?
        - Document Object Model: structured representation of html documents.
          allows js to access html element and styles to manipulate them
    
    Tree structure, generated by browser on html load

    DOM !== JS
    
    DOM methods amd properties are actually part of web APIs
*/

// Selecting and manipulating elements
// document.querySelector(".message").textContent = "🎉 Correct Number";
// console.log(document.querySelector(".message").textContent);

// document.querySelector(".guess").value = 23;
// console.log(document.querySelector(".guess").value);

// Handling click events

// Implement the game logic
let score = 20;
let secretNum = Math.trunc(Math.random() * 20);
let highscore = 0;

const displayMessage = function (message) {
	document.querySelector(".message").textContent = message;
};

const displayScore = function (score) {
	document.querySelector(".score").textContent = score;
};

const displaySecretNum = function (secretNum) {
	document.querySelector(".number").textContent = secretNum;
};

document.querySelector(".check").addEventListener("click", function () {
	const guess = Number(document.querySelector(".guess").value);
	console.log(guess, typeof guess);

	if (!guess) {
		// document.querySelector(".message").textContent = "⛔ No Number";
		displayMessage("⛔ No Number");
	} else if (guess === secretNum) {
		// document.querySelector(".message").textContent = "🎉 Correct Number";
		displayMessage("🎉 Correct Number");
		// document.querySelector(".number").textContent = secretNum;
		displaySecretNum(secretNum);
		document.querySelector("body").style.backgroundColor = "#60b347";
		document.querySelector(".number").style.width = "30rem";

		if (score > highscore) {
			highscore = score;
			document.querySelector(".highscore").textContent = highscore;
		}
	} else if (guess !== secretNum) {
		if (score > 1) {
			// document.querySelector(".message").textContent =
			// 	guess > secretNum ? "📈 Too High!!" : "📉 Too Low!!";
			displayMessage(guess > secretNum ? "📈 Too High!!" : "📉 Too Low!!");
			score--;
			// document.querySelector(".score").textContent = score;
			displayScore(score);
		} else {
			// document.querySelector(".message").textContent = "💥 You lost the game!!";
			displayMessage("💥 You lost the game!!");
			// document.querySelector(".score").textContent = 0;
			displayScore("0");
		}
	}
	//  else if (guess > secretNum) {
	// 	if (score > 1) {
	// 		document.querySelector(".message").textContent = "📈 Too High!!";
	// 		score--;
	// 		document.querySelector(".score").textContent = score;
	// 	} else {
	// 		document.querySelector(".message").textContent = "💥 You lost the game!!";
	// 		document.querySelector(".score").textContent = 0;
	// 	}
	// } else if (guess < secretNum) {
	// 	if (score > 1) {
	// 		document.querySelector(".message").textContent = "📉 Too Low!!";
	// 		score--;
	// 		document.querySelector(".score").textContent = score;
	// 	} else {
	// 		document.querySelector(".message").textContent = "💥 You lost the game!!";
	// 		document.querySelector(".score").textContent = 0;
	// 	}
	// }
});

document.querySelector(".again").addEventListener("click", function () {
	score = 20;
	secretNum = Math.trunc(Math.random() * 20);
	document.querySelector(".guess").value = "";
	// document.querySelector(".score").textContent = score;
	displayScore(score);
	document.querySelector(".number").textContent = "?";
	// document.querySelector(".message").textContent = "Start guessing...";
	displayMessage("Start guessing...");
	document.querySelector("body").style.backgroundColor = "#333";
	document.querySelector(".number").style.width = "15rem";
});
