"use strict";

/*
    What's DOM?
        - Document Object Model: structured representation of html documents.
          allows js to access html element and styles to manipulate them
    
    Tree structure, generated by browser on html load

    DOM !== JS
    
    DOM methods amd properties are actually part of web APIs
*/

// Selecting and manipulating elements
// document.querySelector(".message").textContent = "🎉 Correct Number";
// console.log(document.querySelector(".message").textContent);

// document.querySelector(".guess").value = 23;
// console.log(document.querySelector(".guess").value);

// Handling click events

// Implement the game logic
let score = 20;
const secretNum = Math.trunc(Math.random() * 20);
document.querySelector(".number").textContent = secretNum;

document.querySelector(".check").addEventListener("click", function () {
   const guess = Number(document.querySelector(".guess").value);
   console.log(guess, typeof guess);

   if (!guess) {
      document.querySelector(".message").textContent = "⛔ No Number";
   } else if (guess === secretNum) {
      document.querySelector(".message").textContent = "🎉 Correct Number";
   } else if (guess > secretNum) {
      if (score > 1) {
         document.querySelector(".message").textContent = "📈 Too High!!";
         score--;
         document.querySelector(".score").textContent = score;
      } else {
         document.querySelector(".message").textContent =
            "💥 You lost the game!!";
         document.querySelector(".score").textContent = 0;
      }
   } else if (guess < secretNum) {
      if (score > 1) {
         document.querySelector(".message").textContent = "📉 Too Low!!";
         score--;
         document.querySelector(".score").textContent = score;
      } else {
         document.querySelector(".message").textContent =
            "💥 You lost the game!!";
         document.querySelector(".score").textContent = 0;
      }
   }
});
